name: CI

on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  raspberrypi:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-${{ runner.os }}-${{ hashFiles('**/build_raspberry_pi.sh') }}
          restore-keys: |
            apt-${{ runner.os }}-

      - name: Cache Raspberry Pi OS image
        id: cache-raspios
        uses: actions/cache@v4
        with:
          path: raspios.img.xz
          key: raspios-arm64-2025-12-04-681a775e20b53a9e
          restore-keys: |
            raspios-arm64-2025-12-04-

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -yqq qemu-utils qemu-user-static binfmt-support rsync sudo wget xz-utils pigz mount dosfstools libarchive-tools zerofree util-linux e2fsprogs fdisk
          
      - name: Download Raspberry Pi OS image (if not cached)
        if: steps.cache-raspios.outputs.cache-hit != 'true'
        run: |
          wget -nv -O raspios.img.xz "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2025-12-04/2025-12-04-raspios-trixie-arm64-lite.img.xz"
          echo "681a775e20b53a9e4c7341d748a5a8cdc822039d8c67c1fd6ca35927abbe6290 raspios.img.xz" | sha256sum --check --status

      - name: Save Raspberry Pi OS image to cache
        if: steps.cache-raspios.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: raspios.img.xz
          key: raspios-arm64-2025-12-04-681a775e20b53a9e
          save-always: true

      - name: Build arm64 (Raspberry Pi 4/5) firmware
        run: |
          chmod +x ./build_raspberry_pi.sh
          sudo ./build_raspberry_pi.sh "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2025-12-04/2025-12-04-raspios-trixie-arm64-lite.img.xz" "681a775e20b53a9e4c7341d748a5a8cdc822039d8c67c1fd6ca35927abbe6290" "arm64-raspberrypi"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: anotterkiosk-arm64-raspberrypi
          path: ./anotterkiosk-*.img.xz
          retention-days: 30

      - name: Release build artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          append_body: true
          body_path: ./version-info
          files: |
            ./anotterkiosk-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}